feat/fonts: добавил шрифты #4
pomazkovanton/noiceland pull request #18
Opened 2023-02-17 20:48 UTC by P1xelST

Добавил шрифты в проект :)

2023-02-17 23:30 UTC, arctikbear approved these changes
Всё ок

2023-02-18 10:07 UTC, pomazkovanton requested changes

2023-02-18 10:07 UTC, pomazkovanton commented on src/styles/commons/fonts.css
> +        url('../../assets/fonts/LibreFranklin-Bold.ttf') format('ttf'),
ttf довольно устаревший уже формат, даже woff устарелый. Хватит одного woff для подстраховки woff2. Так что удали везде ttf и файлы шрифта тоже.

2023-02-18 10:07 UTC, pomazkovanton commented on src/styles/commons/fonts.css
> +        url('../../assets/fonts/LibreFranklin-Bold.woff2') format('woff2');
Вроде как порядок имеет значение, поэтому самый лучший и оптимизированный шрифт нужно в начале ставить. А у тебя наоборот, ttf все браузеры поддерживают, полэтому он у тебя самым первым и подключится) Поменяй порядок, сначала woff2, потом woff, а ttf выкини)

2023-02-18 10:07 UTC, pomazkovanton commented on src/styles/pages/index.css
>  body {
Эти стили были для примера рабоиы сборки, по БЭМ не должно быть типа общих стилей, поэтому отдельным коммитом удали все стили из index css, оставь только подключение файлов с переменными и шрифтами

2023-02-18 10:09 UTC, pomazkovanton commented
Сам коммит еще не по коныенции написал, у тебя feat/fonts: добавил шрифты #4, а надо feat: добавить шрифты #4. 

Пишем не название ветки а префикс, например feat, fix, style и тд. и сам коммит в повелительном накланении.

2023-02-18 10:24 UTC, pomazkovanton commented
Не понятно, что исправил, такие коммиты это плозая практика. Переделай номрально. По логике тебе нужно было сделать два коммита:

fix: убрать подключение ttf шрифтов #4 
fix: удалить глобальные стили #4 

Так намного нагляднее же сразу.

2023-02-18 10:25 UTC, pomazkovanton commented
Да и сами файлы шрифтов ttf ты удалил?

2023-02-18 11:59 UTC, pomazkovanton commented on src/styles/pages/index.css
>    display: block;
не посмотрел что тянешь в коммит, из-за этого вместе с husky куча мусора еще в коммите)

2023-02-18 12:00 UTC, P1xelST commented on src/styles/pages/index.css
>    display: block;
ой

2023-02-18 12:00 UTC, P1xelST commented on src/styles/pages/index.css
>    display: block;
:D

2023-02-18 12:01 UTC, merged

2023-02-18 12:01 UTC, P1xelST commented on src/styles/pages/index.css
>    display: block;
0_0 общий сбор в дис