pull request: импортировать все изображения из проекта
pomazkovanton/noiceland pull request #19
Opened 2023-02-17 21:46 UTC by IvannaBalanyuk

Импортировала все изображения + два лого в .svg.
В папке src создала папку accets, а в ней - папку images.
Изображения сжала в Squoosh.

Проверьте, плиз, всё ли ок)

2023-02-17 22:38 UTC, P1xelST reviewed
Вроде бы круто. Вроде бы можно svg файл переместить в папку svg-icons, былоб более читаемо : ) На ваше усмотрение : ) Так тоже круто

2023-02-18 10:00 UTC, pomazkovanton requested changes
Один логотип нужно удалить. SVG цвет можно менять с помощью CSS. Первый вариант это задавать значение для поля fill, а второе в самом svg все цвета поменять на значение currentColor, тогда svg будет принимать цвет родителя. Удали один из svg логотипов. 

Также дублируемые картинки нужно удалить, оставить только в самом большом расширении

2023-02-18 10:26 UTC, IvannaBalanyuk commented
Во втором коммите: удалила дублируемые изображения, оставила те, что в большом разрешении;
 удалила лого для футера, переименовала оставшийся файл лого

2023-02-18 12:04 UTC, pomazkovanton commented
Слишком длинный коммит, из-за этого заголовок полность не влазит, не нужно коммиты делать длинной больше 72 символов. Лучше кратко написать заголовок, сделать интер и уже в теле коммита написать более подробно. И забыла добавить номер ишью на втором коммите)))

2023-02-18 12:04 UTC, merged