pull request: Добавить стили ссылкам
pomazkovanton/noiceland pull request #23
Opened 2023-02-18 21:08 UTC by P1xelST

Тестовая работа, и в стили я только что посмотрел по шрифтам, там сам стайл лин все подвинул при коммите :(

2023-02-18 21:19 UTC, P1xelST reviewed
:rage:  :+1: 
стайллинт опять убрал все изменения что я сделал 
:rage: D:  :D

2023-02-18 21:33 UTC, arctikbear requested changes
Нет файла link.html, вместо него есть link.md, но в нем не видно применения компонента
Создан компонент button - это другая задача.
Семантика названий в модификаторах:
логичнее пары dark-light, black-white

Вопрос по именованию компонента
@pomazkovanton  мы не используем двойные подчеркивания, как в БЭМ?

2023-02-19 04:23 UTC, pomazkovanton requested changes

2023-02-19 04:23 UTC, pomazkovanton commented on src/components/UI/button/button.css
> +.button {
Компонент с кнопкой не входил в твою задачу, это отдельный таск #7. Ты не правильно понял задачу, тебе нужно было описать стили для ссылки, но учесть тот момент, когда вместо <a> будут использовать <button>. Тоесть нужно в стили линк дописать стили которые бы учли это. Чтобы в независ имости от какой тэг ты использовал, твои стили не развалились. Так что это нужно удалить, и добавить пару свойств в link

2023-02-19 04:23 UTC, pomazkovanton commented on src/components/UI/link/_button/link_button.css
> +.link-button {
Это тоже нужно убрать

2023-02-19 04:23 UTC, pomazkovanton commented on src/components/UI/link/_dark/link_dark.css
> +.link-dark {
Не по бэм написано, нужно в твоем если случае написать модификатор в таком виде: _ключ_значение. Тогда у тебя будет такая структура
link
  /color
    link_color_dark.css
    link_color_white.css
  link.css
  kink.md

2023-02-19 04:23 UTC, pomazkovanton commented on src/components/UI/link/_white/link_white.css
> +  text-decoration: none;
text-decoration: none; - повторяется в обоих модификаторах, не лучше его перенести в селектор link?

2023-02-19 04:23 UTC, pomazkovanton commented on src/components/UI/link/link.css
> +.link:hover {
Не все состояния описаны для ссылки (active,  focus и тд)

2023-02-19 04:23 UTC, pomazkovanton commented on src/components/UI/link/link.md
> + - link-dark - модификатор для хедера
Документация мне нравится, круто) Но даже в ней ты пишешь, что модификатор для футера, модификатор для хейдера) Либо пиши, что это белая, а та черная ссылка, либо сам модификатор меняй на _place_header/footer

2023-02-19 04:23 UTC, pomazkovanton commented on src/components/UI/link/link.css
> +  text-align: center;
А зачем ты текст ссылки по центру делаешь?

2023-02-19 04:23 UTC, pomazkovanton commented on src/components/UI/link/link.css
> +
Я бы еще убиралбы внешнию геометрию (margin, padding).

2023-02-19 04:23 UTC, pomazkovanton commented on src/styles/pages/index.css
> +/* подключил кнопку */
Тоже нужно убрать

2023-02-19 13:28 UTC, pomazkovanton requested changes

2023-02-19 13:28 UTC, pomazkovanton commented on src/components/UI/link/link.html
> +<a class="link" href="#">...</a>
Не показал использование модификаторов своих новыых

2023-02-19 13:28 UTC, pomazkovanton commented on src/components/UI/link/link.html
> +<button class="link link_button">...</button>
У тебя нет такого селектора )))

2023-02-19 13:28 UTC, pomazkovanton commented on src/components/UI/link/link.html
> +<!-- Модификаторы для ссылок -->
Делайте одинаково, у одного сейчас и доктайп и стили подключены, а у тебя нет) Договритесь однообразно) Я за то чтобы подключить стили и сделать полноценное демо)

2023-02-19 13:28 UTC, pomazkovanton commented on src/components/UI/link/link.css
> +  background-color: var(--color-main-light);
Я бы убрал цвет от сюда, ты же модификатором его задаешь)

2023-02-19 13:28 UTC, pomazkovanton commented on src/components/UI/link/_color/link_color_white.css
> +  color: var(--color-main-dark);
У тебя белый модификатор меняет на черный цвет, как и черный)

2023-02-20 00:16 UTC, pomazkovanton approved these changes
Всё круто, вроде замечаний так не вижу на первый взгляд) Молодец ))

2023-02-20 11:06 UTC, merged