pull request: добавить универсальные стили для блока Text #1
pomazkovanton/noiceland pull request #24
Opened 2023-02-19 11:00 UTC by arctikbear

2023-02-19 11:38 UTC, pomazkovanton requested changes

2023-02-19 11:38 UTC, pomazkovanton commented on src/components/UI/text/__author/text__author.css
> +  margin: 0;
Сейчас у тебя 5 элементов без блока, такого в БЭМ не бывает, нельзя использовать модификаторы и элементы без блока. Плюс семантика мне не понятна.

Все общие стили для текста нужно вынести в корневой файл text.css, а все стили что разичаются перенести в модификаторы. У твоего блока нет элементов. Например можешь сделать так: text text_type_title или text text_type_paragraph. Надеюсь понятно)

2023-02-19 11:38 UTC, pomazkovanton commented on src/components/UI/text/__theme/text__theme.css
> +  font-family: var(--fonts-libreFranklin);
Сам наверное видишь, сколько раз ты одно и тоже писал)

2023-02-19 11:38 UTC, pomazkovanton commented on src/components/UI/text/text.html
> +<!DOCTYPE html>
Вам нужно определится, либо вы html доку деаете, либо в md) Мне без разницы, гавное чтобы у всех было одинаково, раз мы в одной команде работаем)

2023-02-19 19:37 UTC, AlexeyKrutiakov commented on src/components/UI/text/text.html
> +<!DOCTYPE html>
- поправил структуру БЭМ
- определились, доку пишем в .html

2023-02-19 19:48 UTC, AlexeyKrutiakov commented on src/components/UI/text/__author/text__author.css
> +  margin: 0;
поправил структуру БЭМ

2023-02-20 00:09 UTC, pomazkovanton requested changes

2023-02-20 00:09 UTC, pomazkovanton commented on src/components/UI/text/_type/_title/text_type_title.css
>    font-weight: 400;
font-style: normal;
font-weight: 400;

Можно тоже перенести в блок text и оставить только в .text_type_author, так как она там отличается

2023-02-20 00:09 UTC, pomazkovanton commented on src/components/UI/text/text.html
> +    <link rel="stylesheet" href="./text.css" />
Уже почти круто) Еще небольшое замечание по БЭМ структуре) Файлы модификаторов не нужно ложить каждый в свою папку, достаточно только папки-ключ _type, внутри уже должны лежать просто файлы с css

2023-02-20 11:39 UTC, pomazkovanton requested changes

2023-02-20 11:39 UTC, pomazkovanton commented on src/styles/pages/index.css
> +@import url("../../components/UI/text/text.css");
Не исправил импорты модификаторов, пути то изменились) Еще, нужно отделить свой компонент пустой строкой и сотавить комментарий, что это за компонент. Например // Стили для блока с текстом

2023-02-20 12:03 UTC, merged

2023-02-20 14:28 UTC, AlexeyKrutiakov commented on src/styles/pages/index.css
> +@import url("../../components/UI/text/text.css");
принял, на будущее учту