pull request: добавить шапку сайта
pomazkovanton/noiceland pull request #33
Opened 2023-02-22 13:11 UTC by IvannaBalanyuk

Добавила шапку + прописала стили для body (класс page), чтобы видеть все стили header'а.

2023-02-22 13:48 UTC, P1xelST reviewed
Вроде бы по коду все нормуль. Мне в любом случаее всё понарвиться ! :)

2023-02-22 14:08 UTC, IvannaBalanyuk commented
Исправила ошибку в подсчетах минимальной ширины страницы (не учла отступы по бокам 2*120px).
+ Добавила цвет фона для html (так визуально симпатишнее + визуализирует размеры страницы). Хотя это лишнее, если мы страницу будем делать адаптивной (не помню какой был уговор на эту тему) с относительными единицами.

2023-02-22 16:05 UTC, IvannaBalanyuk commented
Почитала тему Относительные размеры блоков (2 спринт), посмотрела на сайт Нобелевской премии https://www.nobelprize.org/alfred-nobel/ и поняла, что надо переделать шапку и стили для body

2023-02-23 06:44 UTC, pomazkovanton requested changes
Очень достойно) Пару замечаний поправь и будет вообще отлично) Также не забывай ставить номер таска в конце коммита) А то я уже как попугай у вас)) И коммиты нужно писать осмысленно, последний был не поянтно что ты делала)

2023-02-23 06:44 UTC, pomazkovanton commented on src/components/UI/header/header.css
> +.header {
Header это не UI элемент, а полноценный блок / секция сайта, ее аряди ты сможешь использовать на другом сайте, она более или менее уникальная всегда. Поэтому весь блок нужно перенести в родительскую папку components.

2023-02-23 06:44 UTC, pomazkovanton commented on src/components/UI/line/line.css
> +.line {
Лишний элемент, это нужно сделать просто рамкой у шапки сайта. Для этого все блоки внутри Header нужно обернуть в обвертку например div.header__conteiner и ему уже задать центрирование.

2023-02-23 06:44 UTC, pomazkovanton commented on src/index.html
> +    <hr class="line" />
Лишний элемент, это нужно сделать просто рамкой у шапки сайта. Для этого все блоки внутри Header нужно обернуть в обвертку например div.header__conteiner и ему уже задать центрирование.

2023-02-23 06:44 UTC, pomazkovanton commented on src/styles/pages/index.css
> +@import url("../../components/UI/line/line.css");
Лишний элемент, это нужно сделать просто рамкой у шапки сайта. Для этого все блоки внутри Header нужно обернуть в обвертку например div.header__conteiner и ему уже задать центрирование.

2023-02-23 06:44 UTC, pomazkovanton commented on src/components/UI/header/__menu/header__menu.css
> +  justify-content: space-between;
Сейчас от этого свойства нет толка, оно не работает, либо удаляй его, либо задавай ширину для блока)

2023-02-23 06:44 UTC, pomazkovanton commented on src/index.html
> +            <a class="link link_color_dark" href="#">Home</a>
Молодец что использовала уже готовые классы, а не стала заново все писать) Это круто)

2023-02-23 06:44 UTC, pomazkovanton commented on src/components/UI/page/page.css
> +.page {
Это отдельная задача и желательно ее делать одному человеку, когда уже будут готовы и подключены все блокт. Тогда у него будет полная картина, что использовать и какие оступы делать. В твоем случае, нужно добавить еще одну обвертку внутри header c классом header___container и задать ему максимальную ширину и margin: auto. Тогда контент шапки отцентрируется)

2023-02-23 06:44 UTC, pomazkovanton commented on src/components/UI/header/header.css
> +  justify-content: space-between;
![изображение](https://user-images.githubusercontent.com/18042030/220836614-29846806-a20d-4a26-99d9-8e8cc353d714.png)
У тебя переполнение проиходит, а токого не должно быть. Нужно добавить правый внешний оступ для логотипа, чтобы меню к нему не прилипало. И для самого меню flex-wrap, чтобы элементы переносились на новую строку.

2023-02-23 07:47 UTC, IvannaBalanyuk commented on src/components/UI/line/line.css
> +.line {
Ок. Сделала сначала так, потом переделала на line))) думала наругаешь за лишнюю обертку

2023-02-23 07:48 UTC, IvannaBalanyuk commented on src/components/UI/header/header.css
> +.header {
Ок, принято

2023-02-23 07:50 UTC, IvannaBalanyuk commented on src/components/UI/header/__menu/header__menu.css
> +  justify-content: space-between;
Согласна. Не убрала после смены тактики

2023-02-23 07:53 UTC, IvannaBalanyuk commented on src/components/UI/header/header.css
> +  justify-content: space-between;
Ок. Спасибо! Не учла)

2023-02-23 09:39 UTC, IvannaBalanyuk commented
выполнено: переместить папку header в components, удалить line (элемент, стили, импорт), реализовать линию через border, удалить page (класс, стили, импорт), в menu удалить выравнивание контента и устранить переполнение

2023-02-23 12:39 UTC, pomazkovanton commented on src/components/header/header.css
> +  width: 100vw;
Лишнее свойство, или для чего оно тебе?) Я бы убрал, чтобы небыло ничего лишнего)

2023-02-23 12:42 UTC, pomazkovanton commented on src/components/header/header.css
> +  min-height: 91px;
Кто-то просит pixelperfect делать верстку, но я считаю это дурастью, не красиво, да и контент на реальном сайте  врядли будет таким же, как на макете, поэтому делать в пиксель в пиксель, только себя мучать, а выхлопа ноль) Я обычно придерживаюсь такой практики, что всё округлять, не 91 а 90 px не 34, а 35px) Даже если дизайнер не опытный был и задал не округленные величины, я их округляю)

2023-02-23 12:43 UTC, pomazkovanton commented on src/components/header/header.css
> +  min-height: 91px;
Но это просто мнение, не обязательн оисправлять) Вообще нужно будет тоже об этом на созвоне договорится)

2023-02-23 12:48 UTC, pomazkovanton commented on src/components/header/__container/header__container.css
> +  min-height: 90px;
А зачем еще и здесь минимальная высота?)

2023-02-23 14:56 UTC, pomazkovanton commented
Хороший коммит) молодец)

2023-02-23 14:57 UTC, merged