pull request: создать стили для кнопок
pomazkovanton/noiceland pull request #41
Opened 2023-02-27 20:29 UTC by AlexeyKrutiakov

2023-02-28 04:58 UTC, pomazkovanton requested changes
Очень хорошо, доделай там пару замечаний и будем заливать)

2023-02-28 04:58 UTC, pomazkovanton commented on src/components/UI/button/button.css
> +  height: 54px;
Не нужно блокам указывать высоту, так как при увеличение контента внутри кнопки произойдет переполнение. Это нужно удалить и задать высоту паддингами

2023-02-28 04:58 UTC, pomazkovanton commented on src/components/UI/button/button.css
> +  cursor: pointer;
Нужно более явно задать эффект наведения, хоть это и не указано в дизайне, например scale сделать, также как другие ребята сделали. Посмотри какое значение у них и используй у себя такой-же, также не забудь про плавность анимации.

2023-02-28 06:00 UTC, KuzinaAnna approved these changes
Мне все нравится)

2023-02-28 20:05 UTC, AlexeyKrutiakov commented
@pomazkovanton 
Всё исправил

2023-03-01 14:26 UTC, pomazkovanton requested changes

2023-03-01 14:26 UTC, pomazkovanton commented on src/components/UI/button/_scale-font-size/button_scale-font-size.css
> +@keyframes scale-font-size {
А что просто не сделал так? https://codepen.io/geoffgraham/pen/RwZyMZP 

Можно весь код заменить двумя строчками) Или был какой0то замысел?)

2023-03-05 16:39 UTC, AlexeyKrutiakov commented on src/components/UI/button/_scale-font-size/button_scale-font-size.css
> +@keyframes scale-font-size {
@pomazkovanton я, значит, не правильно понял задачу свою. думал, что нужно увеличить только то, что содержится внутри самой кнопки, а не всю кнопку, как это сделать с текстом - я не понимаю все равно

2023-03-11 09:39 UTC, pomazkovanton commented on src/components/UI/button/_scale-font-size/button_scale-font-size.css
> +@keyframes scale-font-size {
Я сам поправил, чтобы задачи другие не блокировать)

2023-03-11 09:40 UTC, merged

2023-03-11 15:38 UTC, AlexeyKrutyakov commented on src/components/UI/button/_scale-font-size/button_scale-font-size.css
> +@keyframes scale-font-size {
при скайлинге кнопка тоже увеличивается, и если её ширина будет равна 100%, появится горизонтальный скролл, я хотел от этого уйти