pull-request: добавить секцию с рекомендуемыми постами
pomazkovanton/noiceland pull request #46
Opened 2023-03-20 20:33 UTC by AlexeyKrutyakov

2023-03-22 12:03 UTC, pomazkovanton requested changes

2023-03-22 12:03 UTC, pomazkovanton commented on src/components/featured-posts/__subtitle/featured-posts__subtitle.css
> +  padding-top: 18px;
Это не паддинг, а марджин должен быть по логике)

2023-03-22 12:03 UTC, pomazkovanton commented on src/components/featured-posts/__theme/featured-posts__theme.css
> +  padding-top: 25px;
Это тоже маррджин)

2023-03-22 12:03 UTC, pomazkovanton commented on src/components/featured-posts/featured-posts.css
> +  margin: 0 auto;
Нужно убрать, это всё задасться родительским контейнером (сеткой страницы)

2023-03-22 20:48 UTC, AlexeyKrutyakov commented on src/index.html
> +  <h1>Template</h1>
исправлено

2023-03-22 20:49 UTC, AlexeyKrutyakov commented on src/index.html
> +    <div class="featured-posts__gallery">
исправлено

2023-03-22 20:49 UTC, AlexeyKrutyakov commented on src/index.html
> +          <h2 class="text text_type_subtitle featured-posts__subtitle">A Brief History of the FIFA World Cup Logo</h2>
исправлено

2023-03-22 20:49 UTC, AlexeyKrutyakov commented on src/index.html
> +      <a href="#" class="featured-posts__link">
исправлено

2023-03-22 20:51 UTC, AlexeyKrutyakov commented on src/components/featured-posts/__author/featured-posts__author.css
> +.featured-posts__author::before {
исправлено

2023-03-22 20:51 UTC, AlexeyKrutyakov commented on src/components/featured-posts/__gallery/featured-posts__gallery.css
> +  justify-content: center;
задал максимальную ширину посту 610px, при ширине, меньшей этого значения все начинает масштабироваться.
не понимаю, что не так сделал - или это нормальное поведение?

2023-03-22 20:51 UTC, AlexeyKrutyakov commented on src/components/featured-posts/__image/featured-posts__image.css
> +  padding-top: 25px;
исправлено

2023-03-22 20:51 UTC, AlexeyKrutyakov commented on src/components/featured-posts/__image/featured-posts__image.css
> +  align-self: center;
исправлено

2023-03-22 20:51 UTC, AlexeyKrutyakov commented on src/components/featured-posts/__subtitle/featured-posts__subtitle.css
> +  padding-top: 18px;
исправлено

2023-03-22 20:52 UTC, AlexeyKrutyakov commented on src/components/featured-posts/__theme/featured-posts__theme.css
> +  padding-top: 25px;
исправлено

2023-03-22 20:52 UTC, AlexeyKrutyakov commented on src/components/featured-posts/__post/featured-posts__post.css
> +.featured-posts__post {
исправлено

2023-03-22 20:52 UTC, AlexeyKrutyakov commented on src/components/featured-posts/featured-posts.css
> +  margin: 0 auto;
исправлено

2023-03-22 20:52 UTC, AlexeyKrutyakov commented on src/components/featured-posts/featured-posts.css
> +  padding-top: 90px;
исправлено

2023-03-23 10:47 UTC, pomazkovanton requested changes
Еще же у нас есть готовый компонент с карточкой, тебе нужно было не писать свои классы а использовать те, что делала Анна https://github.com/pomazkovanton/noiceland/issues/9. Посмотри и попробуй использовать именно их, чтобы у всех было одинаково и не плодить кучу кода. А так сама верстка мне нравится, практически идеал) Молодец, ты хорошо поработал)

2023-03-23 10:47 UTC, pomazkovanton commented on src/styles/pages/index.css
> +@import url("../../components/content/content.css");
Удалить импорт пустого файла нужно)

2023-03-23 10:47 UTC, pomazkovanton commented on src/index.html
> +      <h2 class="text text_type_theme featured-posts__title">Featured posts</h2>
Нужно заголовку паддинг задать или что-то придумать, чтобы с макетом было соответствие) 
![изображение](https://user-images.githubusercontent.com/18042030/227179352-44b157d9-d324-40b1-a4cf-7ac1eda05627.png)

2023-03-23 10:48 UTC, pomazkovanton commented
И да, не забывай в коммитах через пробел ставить номер таска к которому они относятся)

2023-03-23 18:18 UTC, AlexeyKrutyakov commented
omg
эпик фейл
я про то, что Анна уже сделала карточки в #9 
моя ошибка - сделал ветку из main, а не из develop - навсегда запомню.

2023-03-23 18:32 UTC, AlexeyKrutyakov commented
сделал локальную fix: ветку из develop  и смерджил её со своей, все новшества появились и у меня. надеюсь, это правильный ход.

2023-03-23 19:54 UTC, AlexeyKrutyakov commented on src/styles/pages/index.css
> +@import url("../../components/content/content.css");
исправлено

2023-03-23 19:54 UTC, AlexeyKrutyakov commented on src/components/content/content.css
исправлено

2023-03-24 11:50 UTC, pomazkovanton approved these changes
Молодец, хорошая работа) Вообще знатно постарался)

2023-03-24 11:51 UTC, merged